
server:
  port: ${HTTP_PORT:9080}
  tomcat:
    uri-encoding: ${URI_ENCODING:UTF-8}

watsonwork:
  app:
    id: 76815b03-6cf9-4a18-b5b6-63e13035c80e
    secret: ${APP_SECRET}
  webhook:
    id: 5a80d6c4e4b00bc90f8d9b79
    secret: ${WEBHOOK_SECRET}
  api:
    uri: ${WATSON_WORK_API_URI:https://api.watsonwork.ibm.com}
    oauth: ${WATSON_WORK_OAUTH:/oauth/authorize}

data:
  cassandra:
    trigger-config:
      ttl-in-seconds: ${TRIGGER_CONFIG_TTL:#{5 * 60}} # 5 minutes